### ISSUE TITLE
Sind alle eure Slides hier drin? Bin wieder aktuelle Ressurcen am Zusammentragen

### ISSUE THREAD

**Issue by rschaerer** [saezh/web-kurzkurs#1]
Hey @gionkunz und @benib 

Ich hab selbst wieder einen 8 h Kurzkurs an der [@kusntschule-zug](https://github.com/kunstschule-zug) und bin aktuelle Ressourcen am Zusammentragen.

Eure Slides hier sehen supi aus, gefällt mir mega. Nun frage ich mich ob noch weitere unveröffentlichte Edelsteine bei euch auf der Platte rumhängen, die veröffentlicht werden könnten und meinen Studis weiterhelfen könnte?

Lieber Gruss
Roger

PS. Wenn ich auch noch mehr Ressrucen braucht, findet ihr vielleicht was nützliches für eure Studis in meinem Trello Board in der spalte [Ressourcen](https://trello.com/b/hlArimBF/kunstschule-html-css-2016). Vor allem die [Supports](https://trello.com/c/7IyNQ51Z) sind immer hoch im Kurs.

**Comment by benib** [comment]
Ja meines Wissens sind alle da verlinkt.
